# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Identification
CONFIG_ZMK_KEYBOARD_NAME="Edin Macropad"
CONFIG_USB_DEVICE_PRODUCT="Edin Macropad"
CONFIG_USB_DEVICE_MANUFACTURER="Custom"
CONFIG_USB_DEVICE_PID=0x8888
