# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y

# Identification
CONFIG_ZMK_KEYBOARD_NAME="Edin Macropad"
CONFIG_USB_DEVICE_PRODUCT="Edin Macropad"
CONFIG_USB_DEVICE_MANUFACTURER="Custom"

# Force USB CDC (Communication Device Class) for Studio
CONFIG_USB_DEVICE_VID=0x1D50
CONFIG_USB_DEVICE_PID=0x615E